### PR TITLE
Check on startup if TLS issuer exists

### LINKED ISSUE #297: Controller starts if tls issuer does not exist
Priority: Medium

## Expected Behaviour
* Controller should fail to start if the tls issuer does not exist GLBC_TLS_PROVIDER (glbc-tls-provider) 

## Actual Behaviour
* The controller starts but starts but certificates never become ready:

```
$ kubectl get certificates rootdefaultkcp-glbc-user-default-ingress-nondomain -n kcp-glbc -o json | jq .status.conditions
[
  {
    "lastTransitionTime": "2022-07-27T07:49:25Z",
    "message": "Issuing certificate as Secret does not exist",
    "observedGeneration": 1,
    "reason": "DoesNotExist",
    "status": "True",
    "type": "Issuing"
  },
  {
    "lastTransitionTime": "2022-07-27T07:49:25Z",
    "message": "Issuing certificate as Secret does not exist",
    "observedGeneration": 1,
    "reason": "DoesNotExist",
    "status": "False",
    "type": "Ready"
  }
]
```

### Steps to Reproduce the Problem

1. Start the controller with `--glbc-tls-provider=idonotexist`

## Suggested Resolution
* Check on startup that the issuer exists

## Additional Information

* Check was removed in this refactor https://github.com/Kuadrant/kcp-glbc/pull/241

### PR DESCRIPTION
**Pull request by ChristianZaccaria**
Closes #297 

## Description of Changes
* Perform check to TLS Issuer - Controller fails to start if the TLS issuer does not exist.

   What is there now works. But, there might be a better way of doing this startup check.

### CODE REVIEW

File: cmd/kcp-glbc/main.go [hunk 1]
```diff
@@ -181,6 +181,9 @@ func main() {
 
 		ingress.InitMetrics(certProvider)
 
+		err = certProvider.Initialize(ctx)
+		exitOnError(err, "Failed to initialize cert provider")
```
Comment (mikenairn) [inline cmd/kcp-glbc/main.go:185]: @maleck13 Is there a better way of doing these kind of startup checks now? I was unsure since the re-factor of the best approach to take here.

I think `Initialize` is probably the wrong name for this, it's more a preStartCheck, that if it fails the controller should fail to start. The check requires the context, so maybe doing it as part of the [Start](https://github.com/Kuadrant/kcp-glbc/blob/main/cmd/kcp-glbc/main.go#L240) would make more sense?

Comment (maleck13) [reply cmd/kcp-glbc/main.go:185]: The refactor didn't really change anything around start up. Perhaps it could be done as part of ``` NewCertManager ``` or change the name to be something more descriptive ```IssuerExists(ctx)(bool,error)```

File: cmd/kcp-glbc/main.go [hunk 2]
```diff
@@ -181,9 +181,10 @@ func main() {
 
 		ingress.InitMetrics(certProvider)
 
-		err = certProvider.Initialize(ctx)
-		exitOnError(err, "Failed to initialize cert provider")
-
+		check, err := certProvider.IssuerExists(ctx)
+		if check == false {
+			exitOnError(err, "Failed as cert provider does not exist")
+		}
```
Comment (mikenairn) [inline cmd/kcp-glbc/main.go:187]: I think you could just just check for err since you return an error if it doesn't exist and it will cover the case of unexpected errors:

```
_, err := certProvider.IssuerExists(ctx)
exitOnError(err, "Cert provider issuer check failed")
```

File: cmd/kcp-glbc/main.go (hunk 1 above)
Comment (ChristianZaccaria) [reply cmd/kcp-glbc/main.go]: @mikenairn I tried performing the check directly under the `NewCertManager` function in `cert_manager.go` but since it needs the context I can't call it again as it's already being called once in `main.go`.

I did a commit though: I changed the function name to IssuerExists and made it so it also returns a boolean. 

It seems to be working but the check is in `main.go`. Wondering if there's a way of just getting the context.

File: cmd/kcp-glbc/main.go (hunk 2 above)
Comment (ChristianZaccaria) [reply cmd/kcp-glbc/main.go]: I did't see this before. That's perfect, I just refactored the check :+1:

File: pkg/tls/cert_manager.go [hunk 3]
```diff
@@ -102,6 +102,17 @@ func (cm *certManager) Domains() []string {
 	return cm.validDomains
 }
 
+func (cm *certManager) IssuerExists(ctx context.Context) (bool, error) {
+	_, err := cm.certClient.CertmanagerV1().Issuers(cm.certificateNS).Get(ctx, cm.IssuerID(), metav1.GetOptions{})
+	if err != nil {
+		if apierrors.IsNotFound(err) {
```
Comment (maleck13) [inline pkg/tls/cert_manager.go:108]: I think we don't need this check. It should have a good message in the not found error. so we can just return 
```
if err != nil{
return false, err
}
return true, nil

Comment (ChristianZaccaria) [reply pkg/tls/cert_manager.go]: Nice one, you're right, there is a good message there. I just made the changes and tested it :+1:

File: cmd/kcp-glbc/main.go [hunk 4]
```diff
@@ -181,6 +181,9 @@ func main() {
 
 		ingress.InitMetrics(certProvider)
 
+		_, err := certProvider.IssuerExists(ctx)
+		exitOnError(err, "Failed as cert provider does not exist")
```
Comment (mikenairn) [inline cmd/kcp-glbc/main.go:185]: This could fail for other reasons than just the issuer not existing. This message would probably be better as "Failed cert provider issuer check", and the error will give the reason why.

Comment (ChristianZaccaria) [reply cmd/kcp-glbc/main.go]: Ok I understand, perfect thanks Mike, I just made the change there.
