### PR TITLE
Check valid KUBECONFIG in local-setup

### LINKED ISSUE #395: Add KUBECONFIG check to local setup script to avoid using kcp admin config incorrectly
Priority: Low

## Issue Description
If you run `make local-setup` in a terminal where you have exported the KUBECONFIG to point to the kcp admin kubeconfig (`export KUBECONFIG=.kcp/admin.kubeconfig`), it will fail with a confusing error:

```
error: current URL "https://127.0.0.1:46195" does not point to cluster workspace
Killing KCP
make: *** [Makefile:174: local-setup] Error 1
```

The local-setup script expects that you are adding your physical clusters (kind) using either your default KUBECONFIG `~/.kube/config`, or any config other than `.kcp/admin.kubeconfig`

## Suggested Resolution

Add a check to local-setup to make sure KUBECONFIG is not set to `.kcp/admin.kubeconfig`

### PR DESCRIPTION
**Pull request by ChristianZaccaria**
Closes #395 

## Description of Changes
* Check to local-setup: if KUBECONFIG is set to `.kcp/admin.kubeconfig`, the script will exit and display a message.

Message: "Can NOT add physical clusters (kind) if KUBECONFIG is set to .kcp/admin.kubeconfig"

## Thoughts
* Wondering if that message is okay or should I simply say: "KUBECONFIG can not be set to .kcp/admin.kubeconfig".
* Check is placed after KCP is attempting to start so I could use the cleanup() exit function.

### CODE REVIEW

File: utils/local-setup.sh [hunk 1]
```diff
@@ -167,6 +167,12 @@ if ! ps -p ${KCP_PID}; then
   exit 1 #this will trigger cleanup function
 fi
 
+#Check that KUBECONFIG is not set to .kcp/admin.kubeconfig
+if [[ $KUBECONFIG == "${KUBECONFIG_KCP_ADMIN}" ]] ; then
+  echo "Can NOT add physical clusters (kind) if KUBECONFIG is set to .kcp/admin.kubeconfig"
+  exit 1 #this will trigger cleanup function
+fi
+
```
Comment (mikenairn) [inline utils/local-setup.sh:175]: Looks good, but you might want to move it up a bit before we start doing anything https://github.com/Kuadrant/kcp-glbc/blob/2b7e0e949e93a6a21dcc7d2dce4407c81417e82d/utils/local-setup.sh#L157 No point starting kcp and then failing really. Also, could you add the same check into the crc script [here](https://github.com/Kuadrant/kcp-glbc/blob/main/utils/local-setup-add-crc-cluster.sh#L57).

Comment (ChristianZaccaria) [reply utils/local-setup.sh]: Excellent, I just made those changes there.

**Review by mikenairn — APPROVED** [review]
